services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: eseo
      MYSQL_DATABASE: sport_3000
      MYSQL_USER: user
      MYSQL_PASSWORD: eseo
    ports:
      - 3306:3306
    volumes:
      - /home/daigreraphael/Documents/ESEO/FRONT/my-app/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mariadb
    ports:
      - 8080:80
    environment:
      PMA_HOST: mariadb
      PMA_USER: user
      PMA_PASSWORD: eseo

  backend:
    container_name: backend
    build: ./backend/
    depends_on:
      - mariadb
      - phpmyadmin
    restart: always
    ports:
      - 3000:3000
    environment:
      DB_HOST: mariadb
      DB_USER: user
      DB_PASSWORD: eseo
      DB_NAME: sport_3000
    volumes:
      - ./backend:/backend
  
  frontend:
    container_name: frontend
    build: ./frontend/
    depends_on:
      - backend
    restart: always
    ports:
      - 80:80
    volumes:
      - ./frontend:/frontend

volumes:
  db_data: